version: '3.8'
services:
    rabbitmq:
        image: rabbitmq:3-management-alpine
        container_name: rabbitmq
        volumes:
            - ./volumes/rabbitmq/etc:/etc/rabbitmq
            - ./volumes/rabbitmq/data:/var/lib/rabbitmq
            - ./volumes/rabbitmq/logs:/var/log/rabbitmq
        ports:
            - 5672:5672
            - 15672:15672
    redis:
        image: redis
        container_name: redis
        command: ['redis-server', '/usr/local/etc/redis/redis.conf']
        volumes:
            - ./volumes/redis/etc:/usr/local/etc/redis
            - ./volumes/redis/data:/data
        ports:
            - 6379:6379
    xun-worker:
        build: xun-worker
        volumes:
            - ./volumes/xun-worker/data:/data
        depends_on:
            - rabbitmq
            - redis
    flower:
        image: mher/flower
        container_name: flower
        command: ['flower', '--broker=amqp://guest@rabbitmq//']
        ports:
            - 5555:5555
        depends_on:
            - rabbitmq
            - xun-worker
